### ISSUE TITLE
TODO - 1st demo

### ISSUE THREAD

**Issue by blomquiste** [vrncndlr/IV1201#1]
Code structure
- [x] Create suitable file structure
- [x] Start a README (file structure, server instructions, config, osv osv)
- [ ] 

Database stuff
- [x] Create database
- [x] Migrate data of users (to manage login) 
- [ ] 

Frameworks
- [x] Install Node and Express
- [x] Install React

Functionality flow
- [x] LoginView
